FROM debian:buster
RUN apt update -y
RUN apt upgrade -y
RUN apt -y install php7.3-fpm php7.3-common php7.3-mysql php7.3-xml php
RUN apt install nginx -y
RUN apt install openssl
RUN mkdir /etc/nginx/ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/C=MA/ST=SRAGHNA /L=Benguerir /O=1337/OU=Cluster/CN=localhost/emailAddress=admin@localhost.com"
RUN mv /var/www/html/*.html /var/www/html/index.html
COPY ./conf /etc/nginx/sites-enabled

# RUN mv /conf /etc/nginx/sites-enabled

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]